import Head from 'next/head'
import styles from "@/styles/Home.module.css";
import Link from "next/link";


export default function Home() {
    return (
        <>
            <Head>
                <title>NBA</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <section className={styles.headerLayout}>
                <div>
                    <img src="/ball.svg" alt=""/>
                </div>
                <nav className={styles.links}>
                    <Link className={styles.link} href="/team">Teams</Link>
                    <Link className={styles.link} href="/player">Players</Link>
                </nav>
            </section>

        </>
    )
}
