import {IPlayer} from "@/interfaces/IPlayer";
import Head from "next/head";
import {PlayerCard} from "@/components/shared/PlayerCard";
import styles from "../styles/Player.module.css";
import {Header} from "@/components/layout/Header";
import {IconButton} from "@mui/material";
import {BsFillPersonPlusFill} from "react-icons/bs";
import Link from "next/link";

export default function Player({players}: { players: IPlayer[] }) {
    return (
        <>
            <Head>
                <title>NBA</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header></Header>
            <h1 className={styles.title}>
                These &nbsp; are &nbsp; the &nbsp; players &nbsp; that &nbsp; are &nbsp;  in &nbsp; our &nbsp; league
            </h1>
            <div className={styles.buttonContainer}>
                <h2 className={styles.subtitle}> There &nbsp; are &nbsp; {players.length} &nbsp; in &nbsp; our &nbsp; league
                </h2>
                <Link className={styles.link} href="/player/create">
                    <IconButton
                        color="primary"
                        className={styles.button}
                    >
                        <BsFillPersonPlusFill/>

                    </IconButton>
                </Link>
            </div>
            <h3 className={styles.subtitle}> The &nbsp; players &nbsp; are</h3>


            <div className={styles.player}>
                {players.reverse().map((player) => (
                    <PlayerCard
                        key={player.id}
                        player={player}
                    />
                ))}
            </div>
        </>
    )
}

// ServerSideProps
export async function getServerSideProps() {
    const res = await fetch('http://localhost:3000/api/player/')
    const players: IPlayer = await res.json()
    console.log(players)
    return {props: {players}}
}