import Head from "next/head";
import styles from "../styles/Team.module.css";
import {IBasketballTeam} from "@/interfaces/IBasketballTeam";
import {TeamCard} from "@/components/shared/TeamCard";
import {Header} from "@/components/layout/Header";
import Link from "next/link";
import {BsFillPersonPlusFill} from "react-icons/bs";
import {baseUrl} from "@/environments/apiBaseUrl";
import {IconButton} from "@mui/material";

export default function Team({teams}: { teams: IBasketballTeam[] }) {
    return (
        <>
            <Head>
                <title>NBA</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header></Header>

            <h1 className={styles.title}>
                These &nbsp; are &nbsp; the &nbsp; teams &nbsp; that &nbsp; are &nbsp;  in &nbsp; our &nbsp; league
            </h1>
            <div className={styles.buttonContainer}>
                <h2 className={styles.subtitle}> There &nbsp; are &nbsp; {teams.length} &nbsp; in &nbsp; our &nbsp; league
                </h2>
                <Link className={styles.link} href="/team/create">
                    <IconButton
                        color="primary"
                        className={styles.button}
                    >
                        <BsFillPersonPlusFill/>
                    </IconButton>
                </Link>
            </div>
            <div className={styles.team}>
                {teams.map((team) => (
                    <TeamCard
                        key={team.id}
                        team={team}
                    />
                ))}
            </div>
        </>
    )
}

// ServerSideProps
export async function getServerSideProps() {
    const res = await fetch(baseUrl.apiUrl + 'basketball-team/')
    const teams: IBasketballTeam = await res.json()
    console.log(teams)
    return {props: {teams}}
}